### ISSUE TITLE
Possibility to make a POST request

### ISSUE THREAD

**Issue by sylouuu** [dyve/jquery-autocomplete#86]
Hello,

It is annoying, you only doing a GET ajax request.

May you create an option to use POST?

And do not add the params after the url but use the data ajax option.

You are doing:

```
$.ajax({
    url: 'file.php?param1=value1&param2=value2
});
```

Do instead:

```
$.ajax({
    url: 'file.php ',
    data: {
        param1: 'value1',
        param2: 'value2'
    }
});
```

**Comment by cyberzilla** [comment]
is this fix? @sylouuu how to fix this?
